name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade setuptools wheel twine

      - name: Get release version
        id: get_version
        run: |
          RELEASE_VERSION=${GITHUB_REF#refs/tags/v}
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_OUTPUT
          echo "Release version: $RELEASE_VERSION"

      - name: Debug - Check __version__
        run: |
          echo "Content of scrapy_nodriver/__init__.py:"
          cat scrapy_nodriver/__init__.py
          echo "Python import of __version__:"
          python -c "from scrapy_nodriver import __version__; print(__version__)"

      - name: Set package version
        run: |
          echo "PACKAGE_VERSION=${{ steps.get_version.outputs.RELEASE_VERSION }}" >> $GITHUB_ENV
          echo "Package version set to: ${{ steps.get_version.outputs.RELEASE_VERSION }}"

      - name: Verify setup.py version
        run: |
          echo "Content of setup.py:"
          cat setup.py
          SETUP_VERSION=$(PACKAGE_VERSION=${{ steps.get_version.outputs.RELEASE_VERSION }} python setup.py --version)
          echo "Version from setup.py: $SETUP_VERSION"
          echo "GitHub release version: ${{ steps.get_version.outputs.RELEASE_VERSION }}"
          if [ "$SETUP_VERSION" != "${{ steps.get_version.outputs.RELEASE_VERSION }}" ]; then
            echo "Version mismatch! setup.py version does not match GitHub release version."
            exit 1
          fi

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel
          echo "Contents of dist directory:"
          ls -l dist/

      - name: Verify package version
        run: |
          WHEEL_FILENAME=$(ls dist/*.whl)
          WHEEL_VERSION=$(echo $WHEEL_FILENAME | sed -n 's/.*-\(.*\)-py3.*/\1/p')
          echo "Wheel filename: $WHEEL_FILENAME"
          echo "Extracted version: $WHEEL_VERSION"
          if [ "$WHEEL_VERSION" != "${{ steps.get_version.outputs.RELEASE_VERSION }}" ]; then
            echo "Version mismatch! Wheel version does not match GitHub release version."
            exit 1
          fi

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          twine upload --verbose dist/*
